import pandas as pd

df = pd.read_csv('data_sources/population/uk_population_harmonized_age_groups.csv')
print('='*80)
print('ENHANCED Harmonized Population File Summary')
print('='*80)
print(f'\nShape: {df.shape}')
print(f'Years: {df["year"].min()} - {df["year"].max()}')
print(f'Total population 1901: {df[df["year"] == 1901]["population"].sum():,}')
print(f'Total population 2016: {df[df["year"] == 2016]["population"].sum():,}')
print(f'Age groups: {sorted(df["age_group"].unique())}')
print(f'Sex: {sorted(df["sex"].unique())}')
print(f'\nYear range coverage:')
print(f'  1901-2000: From combined_population_data.csv')
print(f'  2001-2016: From populations20012016.xls (newly integrated)')
print('\n' + '='*80)
print('Sample 2001 and 2016 data (after integration):')
print('='*80)
print('\n2001:')
print(df[df['year'] == 2001].head(10).to_string())
print('\n2016:')
print(df[df['year'] == 2016].head(10).to_string())
