"""
ICD-10 Code Reference Mapping
Basic ICD-10 code to description mapping derived from WHO ICD-10 structure.
This provides human-readable descriptions for ICD-10 codes (2001+).

Format: code,description
Add or update entries as needed for your analysis.
"""

# Core ICD-10 Chapter structure for common codes
ICD10_CHAPTERS = {
    'A': 'Infectious and parasitic diseases',
    'B': 'Infectious and parasitic diseases',
    'C': 'Neoplasms (Cancer)',
    'D': 'Diseases of blood/immune/endocrine',
    'E': 'Endocrine, nutritional and metabolic diseases',
    'F': 'Mental and behavioral disorders',
    'G': 'Diseases of the nervous system',
    'H': 'Diseases of the eye/ear',
    'I': 'Diseases of the circulatory system',
    'J': 'Diseases of the respiratory system',
    'K': 'Diseases of the digestive system',
    'L': 'Diseases of the skin',
    'M': 'Diseases of musculoskeletal system',
    'N': 'Diseases of the genitourinary system',
    'O': 'Pregnancy, childbirth and puerperium',
    'P': 'Conditions originating in perinatal period',
    'Q': 'Congenital malformations',
    'R': 'Symptoms, signs and abnormal findings',
    'S': 'Injury, poisoning',
    'T': 'Injury, poisoning and external causes',
    'V': 'External causes - transport accidents',
    'W': 'External causes - accidental',
    'X': 'External causes - intentional',
    'Y': 'External causes - undetermined',
    'Z': 'Factors influencing health status'
}

# Common specific codes (expandable)
COMMON_ICD10_CODES = {
    'A00': 'Cholera',
    'A09': 'Diarrhoea and gastroenteritis',
    'A15': 'Respiratory tuberculosis',
    'A16': 'Respiratory tuberculosis, not confirmed',
    'A37': 'Whooping cough',
    'A39': 'Meningococcal infection',
    'A40': 'Streptococcal sepsis',
    'A41': 'Other sepsis',
    'B15': 'Acute hepatitis A',
    'B16': 'Acute hepatitis B',
    'B17': 'Other acute viral hepatitis',
    'B18': 'Chronic viral hepatitis',
    'B20': 'HIV disease',
    'B21': 'HIV disease',
    'B22': 'HIV disease',
    'B23': 'HIV disease',
    'B24': 'Unspecified HIV disease',
    'C00': 'Malignant neoplasm of lip',
    'C15': 'Malignant neoplasm of oesophagus',
    'C16': 'Malignant neoplasm of stomach',
    'C18': 'Malignant neoplasm of colon',
    'C20': 'Malignant neoplasm of rectum',
    'C25': 'Malignant neoplasm of pancreas',
    'C33': 'Malignant neoplasm of trachea',
    'C34': 'Malignant neoplasm of bronchus and lung',
    'C43': 'Malignant melanoma of skin',
    'C50': 'Malignant neoplasm of breast',
    'C53': 'Malignant neoplasm of cervix uteri',
    'C54': 'Malignant neoplasm of corpus uteri',
    'C55': 'Malignant neoplasm of uterus, part unspecified',
    'C56': 'Malignant neoplasm of ovary',
    'C61': 'Malignant neoplasm of prostate',
    'C64': 'Malignant neoplasm of kidney',
    'C67': 'Malignant neoplasm of bladder',
    'C71': 'Malignant neoplasm of brain',
    'C73': 'Malignant neoplasm of thyroid gland',
    'C81': 'Hodgkin lymphoma',
    'C82': 'Follicular lymphoma',
    'C83': 'Non-follicular lymphoma',
    'C85': 'Other and unspecified types of non-Hodgkin lymphoma',
    'C90': 'Multiple myeloma and malignant plasma cell neoplasms',
    'C91': 'Lymphoid leukaemia',
    'C92': 'Myeloid leukaemia',
    'C95': 'Leukaemia of unspecified cell type',
    'D50': 'Iron deficiency anaemia',
    'D51': 'Vitamin B12 deficiency anaemia',
    'D69': 'Purpura and other haemorrhagic conditions',
    'E10': 'Type 1 diabetes mellitus',
    'E11': 'Type 2 diabetes mellitus',
    'E14': 'Unspecified diabetes mellitus',
    'E66': 'Obesity',
    'E78': 'Disorders of lipoprotein metabolism',
    'F00': 'Dementia in Alzheimer disease',
    'F01': 'Vascular dementia',
    'F03': 'Unspecified dementia',
    'F10': 'Mental and behavioural disorders due to use of alcohol',
    'F11': 'Mental and behavioural disorders due to use of opioids',
    'F20': 'Schizophrenia',
    'F32': 'Depressive episode',
    'F33': 'Recurrent depressive disorder',
    'G00': 'Bacterial meningitis',
    'G03': 'Meningitis',
    'G04': 'Encephalitis, myelitis and encephalomyelitis',
    'G20': 'Parkinson disease',
    'G30': 'Alzheimer disease',
    'G40': 'Epilepsy',
    'G41': 'Status epilepticus',
    'G45': 'Transient cerebral ischaemic attacks',
    'G80': 'Cerebral palsy',
    'I10': 'Essential (primary) hypertension',
    'I20': 'Angina pectoris',
    'I21': 'Acute myocardial infarction',
    'I22': 'Subsequent myocardial infarction',
    'I23': 'Complications following acute myocardial infarction',
    'I24': 'Other acute ischaemic heart diseases',
    'I25': 'Chronic ischaemic heart disease',
    'I50': 'Heart failure',
    'I60': 'Subarachnoid haemorrhage',
    'I61': 'Intracerebral haemorrhage',
    'I62': 'Other nontraumatic intracranial haemorrhage',
    'I63': 'Cerebral infarction',
    'I64': 'Stroke, not specified as haemorrhage or infarction',
    'I65': 'Occlusion of precerebral arteries',
    'I66': 'Occlusion of cerebral arteries',
    'I67': 'Other cerebrovascular diseases',
    'I69': 'Sequelae of cerebrovascular disease',
    'I70': 'Atherosclerosis',
    'I71': 'Aortic aneurysm and dissection',
    'J09': 'Influenza due to identified zoonotic or pandemic virus',
    'J10': 'Influenza due to other identified influenza virus',
    'J11': 'Influenza, virus not identified',
    'J12': 'Viral pneumonia',
    'J13': 'Pneumonia due to Streptococcus pneumoniae',
    'J14': 'Pneumonia due to Haemophilus influenzae',
    'J15': 'Bacterial pneumonia',
    'J16': 'Pneumonia due to other infectious organisms',
    'J18': 'Pneumonia, organism unspecified',
    'J20': 'Acute bronchitis',
    'J40': 'Bronchitis, not specified as acute or chronic',
    'J42': 'Unspecified chronic bronchitis',
    'J43': 'Emphysema',
    'J44': 'Chronic obstructive pulmonary disease',
    'J45': 'Asthma',
    'J46': 'Status asthmaticus',
    'K25': 'Gastric ulcer',
    'K26': 'Duodenal ulcer',
    'K29': 'Gastritis and duodenitis',
    'K40': 'Inguinal hernia',
    'K50': 'Crohn disease',
    'K51': 'Ulcerative colitis',
    'K52': 'Other noninfective gastroenteritis and colitis',
    'K70': 'Alcoholic liver disease',
    'K72': 'Hepatic failure',
    'K73': 'Chronic hepatitis',
    'K74': 'Fibrosis and cirrhosis of liver',
    'K75': 'Other inflammatory liver diseases',
    'K76': 'Other diseases of liver',
    'K80': 'Cholelithiasis',
    'K85': 'Acute pancreatitis',
    'K86': 'Other diseases of pancreas',
    'N00': 'Acute nephritic syndrome',
    'N17': 'Acute renal failure',
    'N18': 'Chronic kidney disease',
    'N19': 'Unspecified kidney failure',
    'O00': 'Ectopic pregnancy',
    'O15': 'Eclampsia',
    'O72': 'Postpartum haemorrhage',
    'O85': 'Puerperal sepsis',
    'P07': 'Disorders related to short gestation and low birth weight',
    'P22': 'Respiratory distress of newborn',
    'P36': 'Bacterial sepsis of newborn',
    'Q21': 'Congenital malformations of cardiac septa',
    'Q25': 'Congenital malformations of great arteries',
    'Q90': 'Down syndrome',
    'R00': 'Abnormalities of heart beat',
    'R09': 'Other symptoms and signs involving the circulatory and respiratory systems',
    'R54': 'Senility',
    'R95': 'Sudden infant death syndrome',
    'R96': 'Other sudden death, cause unknown',
    'R98': 'Unattended death',
    'R99': 'Ill-defined and unknown cause of mortality',
    'S00': 'Superficial injury of head',
    'S06': 'Intracranial injury',
    'S70': 'Superficial injury of hip and thigh',
    'S72': 'Fracture of femur',
    'T14': 'Injury of unspecified body region',
    'T36': 'Poisoning by systemic antibiotics',
    'T39': 'Poisoning by nonopioid analgesics',
    'T40': 'Poisoning by narcotics and psychodysleptics',
    'T42': 'Poisoning by antiepileptic and sedative-hypnotic drugs',
    'T43': 'Poisoning by psychotropic drugs',
    'T50': 'Poisoning by diuretics and other unspecified drugs',
    'T71': 'Asphyxiation',
    'V01': 'Pedestrian injured in collision with pedal cycle',
    'V02': 'Pedestrian injured in collision with two- or three-wheeled motor vehicle',
    'V09': 'Pedestrian injured in other transport accidents',
    'V19': 'Pedal cyclist injured in transport accident',
    'V29': 'Motorcycle rider injured in transport accident',
    'V49': 'Car occupant injured in transport accident',
    'V89': 'Motor-vehicle accident',
    'W00': 'Fall on same level involving ice and snow',
    'W01': 'Fall on same level from slipping, tripping and stumbling',
    'W10': 'Fall on and from stairs and steps',
    'W19': 'Unspecified fall',
    'W50': 'Hit, struck, kicked by another person',
    'W65': 'Drowning and submersion while in bath-tub',
    'W67': 'Drowning and submersion while in swimming pool',
    'W74': 'Unspecified drowning and submersion',
    'W75': 'Accidental suffocation and strangulation in bed',
    'W76': 'Other accidental hanging and strangulation',
    'W78': 'Inhalation of gastric contents',
    'W79': 'Inhalation and ingestion of food causing obstruction of respiratory tract',
    'X40': 'Accidental poisoning by nonopioid analgesics',
    'X41': 'Accidental poisoning by antiepileptic drugs',
    'X42': 'Accidental poisoning by narcotics and psychodysleptics',
    'X44': 'Accidental poisoning by other drugs',
    'X45': 'Accidental poisoning by alcohol',
    'X60': 'Intentional self-poisoning by nonopioid analgesics',
    'X61': 'Intentional self-poisoning by antiepileptic drugs',
    'X62': 'Intentional self-poisoning by narcotics',
    'X64': 'Intentional self-poisoning by other drugs',
    'X65': 'Intentional self-poisoning by alcohol',
    'X70': 'Intentional self-harm by hanging, strangulation and suffocation',
    'X80': 'Intentional self-harm by jumping from a high place',
    'Y10': 'Poisoning by nonopioid analgesics, undetermined intent',
    'Y11': 'Poisoning by antiepileptic drugs, undetermined intent',
    'Y12': 'Poisoning by narcotics, undetermined intent',
    'Y14': 'Poisoning by other drugs, undetermined intent',
    'Y15': 'Poisoning by alcohol, undetermined intent',
    'Y34': 'Unspecified event, undetermined intent',
    'Z38': 'Liveborn infants according to place of birth',
}


def get_icd10_description(code):
    """
    Return a description for an ICD-10 code.
    Uses specific mapping if available, otherwise chapter-level description.
    """
    code = str(code).strip().upper()
    
    # Try exact match first
    if code in COMMON_ICD10_CODES:
        return COMMON_ICD10_CODES[code]
    
    # Try base code (e.g., 'A091' -> 'A09')
    base_code = code[:3]
    if base_code in COMMON_ICD10_CODES:
        return COMMON_ICD10_CODES[base_code] + f' ({code})'
    
    # Fall back to chapter description
    chapter = code[0] if code else '?'
    chapter_desc = ICD10_CHAPTERS.get(chapter, 'Unspecified condition')
    return f'{chapter_desc} ({code})'


if __name__ == '__main__':
    # Test
    print(get_icd10_description('A09'))
    print(get_icd10_description('A091'))
    print(get_icd10_description('C34'))
    print(get_icd10_description('I21'))
    print(get_icd10_description('Z999'))
